### ISSUE TITLE
Choose APIs

### ISSUE THREAD

**Issue by ChristopherLawn** [ChristopherLawn/team-1-dinner-movie#1]
* Choose and test free movie API
* Choose and test free restaurants API

**Comment by katieclauswell** [comment]
Assigning Daniel who is researching movie APIs.

**Comment by ChristopherLawn** [comment]
APIs Chosen
For restaurant searches
* Travel Advisor API - (https://rapidapi.com/apidojo/api/travel-advisor)
For movie information
* OMDb API - The Open Movie Database (http://www.omdbapi.com/)
