### ISSUE TITLE
Create CSS Styles

### ISSUE THREAD

**Issue by ChristopherLawn** [ChristopherLawn/team-1-dinner-movie#3]
* Use https://materializecss.com/ for styling as replacement for Bootstrap
* Header
   * Working Title: "Dinner & A Movie!"
* Dropdown menu for restaurant cuisine types
* Interactive date-picker for choosing date
* Zip code input
* Container showing restaurant list/links
* Container showing local movie times
* Footer
   * "Made with Love by Team 1"

**Comment by ChristopherLawn** [comment]
Added font-family "Anton" to style the section headers, search input placeholders, and buttons.

**Comment by zaclark369** [comment]
Created independent classes for generated docs for styling elements.
