### ISSUE TITLE
Create JS Functions

### ISSUE THREAD

**Issue by ChristopherLawn** [ChristopherLawn/team-1-dinner-movie#4]
* Restaurant cuisine type options:
   * Hard-coded in HTML?
   * Dynamically created using JS?
* Search function:
   * Combines cuisine type & date
   * Searches for cuisine type & date to find restaurants and movie times in a specific zip code
 * In restaurants container:
   * Shows list of cuisine-type restaurants in that zip code (**Decision to make: max of 5 listed?**)
 * In movie times container:
    * (**Decision to make: show list of local theaters?  OR show list of movies at the closest/largest theater in/near that zip code?**)

**Comment by katieclauswell** [comment]
List of cuisines available for filter: [https://developer-tripadvisor.com/content-api/business-content/cuisines/](https://developer-tripadvisor.com/content-api/business-content/cuisines/)

**Comment by ChristopherLawn** [comment]
Client-side storage JS functionalities:
* Client-side storage using localStorage of zip code searches
* Dynamically creating zip code buttons when the user searches a zip code. Clicking these buttons also allow the user to search that same zip code again.
* Added a "Clear Search History" button.  This button:
    * Is hidden when the user first visits the page
    * Appears when the user completes their first zip code search
    * Appears and persists if/when the user refreshes the page and there are zip code searches saved in localStorage
    * When clicked, this button:
        * Clears localStorage
        * Hides the "Zip Searches" search history container
        * Deletes and hides the zip code buttons
        * Hides itself until the user completes a new zip code search
        * Automatically refreshes the page
